import org.apache.hadoop.ozone.protocolPB.StorageContainerLocationProtocolServerSideTranslatorPB;
public class FunctionUse33 {
public void funcUse() {
StorageContainerLocationProtocolServerSideTranslatorPB storagecontainerlocationprotocolserversidetranslatorpb = new StorageContainerLocationProtocolServerSideTranslatorPB();
storagecontainerlocationprotocolserversidetranslatorpb.allocatePipeline(null,null);
}
}