import org.apache.hadoop.hdds.protocol.proto.StorageContainerLocationProtocolProtos.GetContainerWithPipelineRequestProtoOrBuilder;
public class FunctionUse12545 {
public void funcUse() {
GetContainerWithPipelineRequestProtoOrBuilder getcontainerwithpipelinerequestprotoorbuilder = new GetContainerWithPipelineRequestProtoOrBuilder();
getcontainerwithpipelinerequestprotoorbuilder.hasTraceID();
}
}