import org.apache.hadoop.hdds.scm.protocolPB.StorageContainerLocationProtocolClientSideTranslatorPB;
public class FunctionUse14456 {
public void funcUse() {
StorageContainerLocationProtocolClientSideTranslatorPB storagecontainerlocationprotocolclientsidetranslatorpb = new StorageContainerLocationProtocolClientSideTranslatorPB();
storagecontainerlocationprotocolclientsidetranslatorpb.queryNode(null,null,null);
}
}