import org.apache.hadoop.hdds.scm.protocolPB.StorageContainerLocationProtocolClientSideTranslatorPB;
public class FunctionUse14469 {
public void funcUse() {
StorageContainerLocationProtocolClientSideTranslatorPB storagecontainerlocationprotocolclientsidetranslatorpb = new StorageContainerLocationProtocolClientSideTranslatorPB();
storagecontainerlocationprotocolclientsidetranslatorpb.close();
}
}