import org.apache.hadoop.hdds.scm.protocolPB.ScmBlockLocationProtocolClientSideTranslatorPB;
public class FunctionUse14447 {
public void funcUse() {
ScmBlockLocationProtocolClientSideTranslatorPB scmblocklocationprotocolclientsidetranslatorpb = new ScmBlockLocationProtocolClientSideTranslatorPB();
scmblocklocationprotocolclientsidetranslatorpb.transformServiceException(null);
}
}