import org.apache.hadoop.hdds.scm.protocolPB.StorageContainerLocationProtocolClientSideTranslatorPB;
public class FunctionUse14470 {
public void funcUse() {
StorageContainerLocationProtocolClientSideTranslatorPB storagecontainerlocationprotocolclientsidetranslatorpb = new StorageContainerLocationProtocolClientSideTranslatorPB();
storagecontainerlocationprotocolclientsidetranslatorpb.allocateContainer(null,null,null);
}
}