import org.apache.hadoop.ozone.protocolPB.StorageContainerLocationProtocolServerSideTranslatorPB;
public class FunctionUse31 {
public void funcUse() {
StorageContainerLocationProtocolServerSideTranslatorPB storagecontainerlocationprotocolserversidetranslatorpb = new StorageContainerLocationProtocolServerSideTranslatorPB();
storagecontainerlocationprotocolserversidetranslatorpb.deleteContainer(null,null);
}
}