import org.apache.hadoop.ozone.protocolPB.StorageContainerLocationProtocolServerSideTranslatorPB;
public class FunctionUse34 {
public void funcUse() {
StorageContainerLocationProtocolServerSideTranslatorPB storagecontainerlocationprotocolserversidetranslatorpb = new StorageContainerLocationProtocolServerSideTranslatorPB();
storagecontainerlocationprotocolserversidetranslatorpb.allocateContainer(null,null);
}
}