import org.apache.hadoop.ozone.protocolPB.StorageContainerLocationProtocolServerSideTranslatorPB;
public class FunctionUse26 {
public void funcUse() {
StorageContainerLocationProtocolServerSideTranslatorPB storagecontainerlocationprotocolserversidetranslatorpb = new StorageContainerLocationProtocolServerSideTranslatorPB();
storagecontainerlocationprotocolserversidetranslatorpb.inChillMode(null,null);
}
}