import org.apache.hadoop.hdds.scm.protocolPB.StorageContainerLocationProtocolClientSideTranslatorPB;
public class FunctionUse14462 {
public void funcUse() {
StorageContainerLocationProtocolClientSideTranslatorPB storagecontainerlocationprotocolclientsidetranslatorpb = new StorageContainerLocationProtocolClientSideTranslatorPB();
storagecontainerlocationprotocolclientsidetranslatorpb.getScmInfo();
}
}