import org.apache.hadoop.hdds.protocol.proto.StorageContainerLocationProtocolProtos.GetContainerWithPipelineRequestProtoOrBuilder;
public class FunctionUse12547 {
public void funcUse() {
GetContainerWithPipelineRequestProtoOrBuilder getcontainerwithpipelinerequestprotoorbuilder = new GetContainerWithPipelineRequestProtoOrBuilder();
getcontainerwithpipelinerequestprotoorbuilder.getTraceIDBytes();
}
}